Repository stefanzweifel/laravel-backup-restore, pull requests merged in 2024-01, with the labels that each got.

#55 Disable Process Timeout when importing Database backup
  src/Databases/DbImporter.php
  src/HealthChecks/Result.php
  tests/Commands/RestoreCommandTest.php
Labels: changelog:fixed

#62 Better unpacked dump detection
  src/Actions/ImportDumpAction.php
  src/PendingRestore.php
Labels: changelog:changed

#61 Add Support to import bz2 compressed database dumps
  src/Databases/MySql.php
  src/Databases/PostgreSql.php
  src/Databases/Sqlite.php
  src/Exceptions/ImportFailed.php
  src/PendingRestore.php
  tests/Databases/MySqlTest.php
  tests/Databases/PostgreSqlTest.php
  tests/Databases/SqliteTest.php
  tests/storage/Laravel/2023-01-28-mysql-compression-no-encryption.sql.bz2
  tests/storage/Laravel/2023-02-28-sqlite-compression-no-encryption.sql.bz2
  tests/storage/Laravel/2023-03-04-pgsql-compression-no-encryption.sql.bz2
Labels: changelog:added
